# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from splitfleet.proto import stage_worker_pb2 as stage__worker__pb2


class StageWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlan = channel.unary_unary(
                '/stage_worker.StageWorker/RegisterPlan',
                request_serializer=stage__worker__pb2.RegisterPlanRequest.SerializeToString,
                response_deserializer=stage__worker__pb2.RegisterPlanResponse.FromString,
                )
        self.ExecuteStage = channel.unary_unary(
                '/stage_worker.StageWorker/ExecuteStage',
                request_serializer=stage__worker__pb2.StageExecutionRequest.SerializeToString,
                response_deserializer=stage__worker__pb2.StageExecutionResponse.FromString,
                )
        self.BackwardStage = channel.unary_unary(
                '/stage_worker.StageWorker/BackwardStage',
                request_serializer=stage__worker__pb2.StageBackwardRequest.SerializeToString,
                response_deserializer=stage__worker__pb2.StageBackwardResponse.FromString,
                )
        self.ClearExecution = channel.unary_unary(
                '/stage_worker.StageWorker/ClearExecution',
                request_serializer=stage__worker__pb2.ClearExecutionRequest.SerializeToString,
                response_deserializer=stage__worker__pb2.ClearExecutionResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/stage_worker.StageWorker/Heartbeat',
                request_serializer=stage__worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=stage__worker__pb2.HeartbeatResponse.FromString,
                )


class StageWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackwardStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StageWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlan,
                    request_deserializer=stage__worker__pb2.RegisterPlanRequest.FromString,
                    response_serializer=stage__worker__pb2.RegisterPlanResponse.SerializeToString,
            ),
            'ExecuteStage': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStage,
                    request_deserializer=stage__worker__pb2.StageExecutionRequest.FromString,
                    response_serializer=stage__worker__pb2.StageExecutionResponse.SerializeToString,
            ),
            'BackwardStage': grpc.unary_unary_rpc_method_handler(
                    servicer.BackwardStage,
                    request_deserializer=stage__worker__pb2.StageBackwardRequest.FromString,
                    response_serializer=stage__worker__pb2.StageBackwardResponse.SerializeToString,
            ),
            'ClearExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearExecution,
                    request_deserializer=stage__worker__pb2.ClearExecutionRequest.FromString,
                    response_serializer=stage__worker__pb2.ClearExecutionResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=stage__worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=stage__worker__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stage_worker.StageWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StageWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stage_worker.StageWorker/RegisterPlan',
            stage__worker__pb2.RegisterPlanRequest.SerializeToString,
            stage__worker__pb2.RegisterPlanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stage_worker.StageWorker/ExecuteStage',
            stage__worker__pb2.StageExecutionRequest.SerializeToString,
            stage__worker__pb2.StageExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BackwardStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stage_worker.StageWorker/BackwardStage',
            stage__worker__pb2.StageBackwardRequest.SerializeToString,
            stage__worker__pb2.StageBackwardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stage_worker.StageWorker/ClearExecution',
            stage__worker__pb2.ClearExecutionRequest.SerializeToString,
            stage__worker__pb2.ClearExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stage_worker.StageWorker/Heartbeat',
            stage__worker__pb2.HeartbeatRequest.SerializeToString,
            stage__worker__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
